### ISSUE TITLE
change in recommended usage BlockingScheduler vs BackgroundScheduler

### ISSUE THREAD

**Issue by niconil** [jcass77/django-apscheduler#101]
I use django_apscheduler 0.3.0 in my django project 

i discover recently the release 0.4.2 and i notice the change recommended to launch the scheduler by management command
can you give more details about this change

do i need to follow this recommendation if i upgrade to 0.4.2 ?
what is the risk of keeping a background scheduler ?

**Comment by jcass77** [comment]
All of the risks (that I am aware of) are listed in the [caveats](https://github.com/jarekwg/django-apscheduler#caveats) section of the readme.

It really depends on your specific use case and deployment - if your current approach is working for you then everything should continue to work just as well under 0.4.2.
