### ISSUE TITLE
Feature Request: Job Timeout

### ISSUE THREAD

**Issue by MohammadJamali** [jcass77/django-apscheduler#103]
Hi,

Sometimes a job is depend on other external and third-party libraries/devices and can be freeze forever because of a link/hardware failure or network error.
But i can compute a rational and reasonable runtime for it, as an example, 20 mins. if the job don't return any result/exception it might be considered as `Not Responding` so it need a hard restart.

it would be nice to have a `timeout` property for each job, something like:

```
scheduler.add_job(
            _job,
            trigger=CronTrigger(minute="*/1"), 
            timeout=Timeout(timedelta(seconds=360), TimeoutAction.[HardReset, ForceStop, Delete, ...]),
            ...
        )
```

Thanks

**Comment by jcass77** [comment]
django-apscheduler is just an [APScheduler job store](https://apscheduler.readthedocs.io/en/latest/extending.html#custom-job-stores) and does not control the actual running of APScheduler jobs.

You probably want to submit this feature request upstream, or look at combining APScheduler with a more full featured background task processing library like [Dramatiq](https://dramatiq.io) (which does cater for runtime timeouts).
