### ISSUE TITLE
managing multiple jobstores

### ISSUE THREAD

**Issue by niconil** [jcass77/django-apscheduler#104]
i have recently upgraded to v0.4.2 of django-apscheduler 
i have isolated the runapscheduler management command in a specific container
i need some scalability

i imagine to split my jobs in two groups
to launch two containers with a distinct management command but the DjangoJobStore is unique and i suppose it's not possible to run specific jobs on each process

i read the FAQ entry ['How do I share a single job store among one or more worker processes'](https://apscheduler.readthedocs.io/en/stable/faq.html#how-do-i-share-a-single-job-store-among-one-or-more-worker-processes) on apscheduler doc site

i search how to create two jobstores ... but no success

how to split my planified jobs in two or more groups and have each process managing only one group of jobs ?
having many jobstore is not an issue for me

**Comment by jcass77** [comment]
Creating multiple job stores is not supported by django-apscheduler and I am not sure that doing so would be aligned with how APScheduler is supposed to be used (the job store is just there to keep track of scheduled jobs, not deal with how they are actually executed).

If your scaling needs cannot be met via [APScheduler's standard](https://apscheduler.readthedocs.io/en/stable/userguide.html?highlight=ThreadPoolExecutor#configuring-the-scheduler)  `ThreadPoolExecutor` or `ProcessPoolExecutor` then it is probably time to incorporate a distributed background task processing library in your application to do the heavy lifting for you.

I like [Dramatiq](https://dramatiq.io) but there are probably others.
