### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by oneandonlyonebutyou** [jcass77/django-apscheduler#105]
> This management command should be invoked via ./manage.py runapscheduler whenever the web server serving your Django application is started. The details of how and where this should be done is implementation specific, and depends on which web server you are using and how you are deploying your application to production. For most people this should involve configuring a supervisor process of sorts.

I do not fully understand this. 
I am trying to (it is super basic)
1: Start the website and scheduler jobs
2: Take a look at jobs scheduled (within 2 days just to see if anything went wrong )    

Please help me

**Comment by jcass77** [comment]
If you are working in your development environment, then just run `./manage.py runapscheduler` in a terminal window on your OS to start the scheduler.

**Comment by oneandonlyonebutyou** [comment]
thanks
