### ISSUE TITLE
How am I supposed to extend DjangoJobExecution

### ISSUE THREAD

**Issue by oneandonlyonebutyou** [jcass77/django-apscheduler#106]
When I execute a job, I have some return values  (number of item found, etc) which I like to keep track of when I am listing the history jobs..

I even thought of raising an exception with my return value, but it is very ugly and I do not see the status anymore. 

How am I supposed to do that?
Is there any way I could extend the object to keep track of the return values as well (or the result of the job)?
Is there any way I could get job_id to map it a one-to-one table to keep track of all I like based on that execution?

**Comment by jcass77** [comment]
This GitHub issue tracking system is for logging demonstrable bugs in django-apscheduler only and I unfortunately do not have the capacity to address general Django / APScheduler support questions here.

You may want to look at writing a [custom APScheduler executor](https://apscheduler.readthedocs.io/en/latest/extending.html?highlight=result#custom-executors) as a start but there are probably various other ways in which the same can be achieved.
