### ISSUE TITLE
When the system time changes, the timing task is not executed!

### ISSUE THREAD

**Issue by LinanV** [jcass77/django-apscheduler#107]
Hi, Team:
  When I modify the system time, which is smaller than before, the scheduled task will not be executed according to the original logic.

my code:
...
scheduler.add_job(
    refresh_safety_ability_status,
    trigger=CronTrigger(second="*/10"),
    id='refresh_safety_ability_status',
    max_instances=1,
    replace_existing=True,
) 

I want to execute task at every 10 seconds

How to handle this questions, could you help me?

Thanks

**Comment by jcass77** [comment]
It does not sound too surprising that APScheduler will start to miss job executions if the underlying system time (that it relies on) changes unexpectedly.

Have a look at logging this at the [APScheduler project](https://github.com/agronholm/apscheduler) up stream if you think this behaviour is a bug.
