### ISSUE TITLE
[Errno 13] Permission denied: '/Users/xxx/text_task.log'

### ISSUE THREAD

**Issue by iHTCboy** [jcass77/django-apscheduler#109]
macOS 10.15.6

```
  File "/Users/xxx/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/xxxx/utils/LogUtil.py", line 45, in write_log
    file_handler = open(log_file_path, 'a', encoding='utf-8')
```

how to fix denied .log file ?

**Comment by jcass77** [comment]
This issue seems related to the local file permissions on your operating system, and not django-apscheduler.

You should be able to find more information on how to change local file permissions on OSX with a quick internet search.

**Comment by iHTCboy** [comment]
@jcass77 thanks~   

Log files created by scripts cannot be written to .log。
