### ISSUE TITLE
bug when  date rolling

### ISSUE THREAD

**Issue by netzkr** [jcass77/django-apscheduler#123]
use mariadb, mysqlclient
when I change system date 
django apscheduler fails to the db connection
and never recovers.
other django and db connection
to the maria db never  fails except django apscheduler

MySQL server has gone away

tested on win10 
by changing system calendar panel

**Comment by jcass77** [comment]
See #107. Changing system date / time while APScheduler is running will affect job scheduling and execution, and is probably not a good idea.
