### ISSUE TITLE
db disconnected and retry?

### ISSUE THREAD

**Issue by netzkr** [jcass77/django-apscheduler#124]
Scenario

1. launch django
2. DB Backend is maria DB
3. schedule some watchdog function every 5 seconds.
4. django-apscheduler runs well. and DJango web service is well.
5. Shutdown Maria DB, and then restart DB
6. DJango web service is well again.
7. But DJango-apscheduler is not working well.
   It fails wehn call every db related function. even though DB is restarted.

django-apscheduler can detect DB connection event? and retry re-connect?

Thanks for your contribution~!

**Comment by jcass77** [comment]
django-apscheduler relies on the standard Django ORM and should behave in exactly the same way as any other Django application under the circumstances that you described above.

I unfortunately do not have the bandwidth to answer general Django questions here and you might want to try one of the Django forums or mailing lists instead, or refer to the  [section on databases](https://docs.djangoproject.com/en/3.1/ref/databases/) in the official Django docs.

The behavior that you are seeing is probably due to a combination of DB version, DB drivers, Django backend and Django configuration settings.

**Comment by netzkr** [comment]
I Hope you will support like DJangoDBRetryJobStore.


Below is my humble code.


Thanks for your work.



class DjangoDBRetryJobStore(DjangoJobStore):

    def __init__(self, pickle_protocol: int = pickle.HIGHEST_PROTOCOL):

        super().__init__(pickle_protocol=pickle_protocol)



    @classmethod

    def retry_db_connection(cls):

        from django.db import connections



        conn: BaseDatabaseWrapper

        for conn in connections.all():

            conn.close_if_unusable_or_obsolete()

            conn.connect()



    @classmethod

    def check_db_connection(cls):

        try:

            count = DjangoJob.objects.all().count()

        except Exception as e:

            cls.retry_db_connection()



    @classmethod

    def handle_execution_event(cls, event: JobExecutionEvent) -> Union[int,
None]:

        cls.check_db_connection()



        return super().handle_execution_event(event)



    def lookup_job(self, job_id: str) -> Union[None, AppSchedulerJob]:

        self.__class__.check_db_connection()



        return super().lookup_job(job_id=job_id)



    def get_due_jobs(self, now) -> List[AppSchedulerJob]:

        self.__class__.check_db_connection()



        return super().get_due_jobs(now)



    def get_next_run_time(self):

        self.__class__.check_db_connection()



        return super().get_next_run_time()



    def add_job(self, job: AppSchedulerJob):

        self.__class__.check_db_connection()



        super().add_job(job)



    def update_job(self, job: AppSchedulerJob):

        self.__class__.check_db_connection()



        super().update_job(job)



    def remove_job(self, job_id: str):

        self.__class__.check_db_connection()

        super().remove_job(job_id)



    def remove_all_jobs(self):

        self.__class__.check_db_connection()



        return super().remove_all_jobs()



    def _get_jobs(self, **filters):

        self.__class__.check_db_connection()



        return super()._get_jobs(**filters)

2020년 11월 2일 (월) 오전 12:49, John Cass <notifications@github.com>님이 작성:
