### ISSUE TITLE
Add new job

### ISSUE THREAD

**Issue by zN3utr4l** [jcass77/django-apscheduler#127]
I tried to implement django-apscheduler from your folder, copying and pasting the pieces of code in my app, I launch the command python manage.py migrate, it creates the tables for me but when I go to insert through the form / admin the output is this .

Do I have to run some custom Django management commands first?

**To Reproduce**
1. 'python manage.py runserver'
2. Go to 'localhost:8000/admin'
3. Click on 'Django APScheduler'
4. Click on  'Django jobs'
5. See error "Could not find job 1 in the database! Skipping execution...
![Cattura](https://user-images.githubusercontent.com/73225008/98828148-03799400-2438-11eb-8d3c-7e4ddf2e6c16.PNG)
"

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/admin/django_apscheduler/djangojob/
System Version: Win 10
Django Version: 3.0.7
Python Version: 3.7.9

**Comment by jcass77** [comment]
That error seems to indicate that the `DjangoJob` table does not exist - are you sure that the migrations were completed successfully?

Once that error is resolved, the proper way to schedule a job is via a custom management command - please refer to the README, which contains an example implementation in `runapscheduler.py`.

The Django admin pages can only be used to view jobs and job executions, not to schedule new jobs or edit / remove jobs (APScheduler does not currently provide an inter-process synchronization and signalling scheme that would enable the scheduler to be notified when a job has been added, modified, or removed from a job store).

> I tried to implement django-apscheduler from your folder, copying and pasting the pieces of code in my app

Not sure I follow, but the canonical way to install django-apscheduler is using pip (e.g. `pip install django-apscheduler`) and then just creating the `runapscheduler.py` management command in your project.

**Comment by zN3utr4l** [comment]
Sorry i update my issue but i think is for this "**The Django admin pages can only be used to view jobs and job executions, not to schedule new jobs or edit / remove jobs (APScheduler does not currently provide an inter-process synchronization and signalling scheme that would enable the scheduler to be notified when a job has been added, modified, or removed from a job store).**"
![Cattura](https://user-images.githubusercontent.com/73225008/98828442-610de080-2438-11eb-86e7-6f2081a8c8a9.PNG)

This is my folder project, where i need to implement runapscheduler.py, sorry for this stupid questions but im new in django and scheduled jobs

**Comment by jcass77** [comment]
@zN3utr4l, the README contains links to all of the documentation that you need to help you get started. I regret that I do not have the capacity to provide general Django assistance here.

Have a look at https://docs.djangoproject.com/en/dev/howto/custom-management-commands/
