### ISSUE TITLE
Adding job to jobstore multiple times

### ISSUE THREAD

**Issue by Mastersam07** [jcass77/django-apscheduler#131]
A job gets added to the jobstore twice allowing the same job to be executed twice. Below is an image

![image](https://user-images.githubusercontent.com/31275429/105384849-8f8e0180-5bc7-11eb-8d27-a1fd787629b8.png)

**To Reproduce, here is a snapshot of the code:**
```py
Steps to reproduce the behavior:
from package1.tweet_handlers import tweet_scheduler
from apscheduler.schedulers.background import BackgroundScheduler
from django.conf import settings
from django_apscheduler.jobstores import register_events, register_job, DjangoJobStore


def start():
    scheduler = BackgroundScheduler(settings.SCHEDULER_CONFIG)
    # scheduler.add_jobstore(DjangoJobStore(), "default")
    scheduler.add_job(
        tweet_scheduler, 'interval', minutes=5)
    register_events(scheduler)
    scheduler.start()
```
**Expected behaviour**
The job is meant to be added to the jobstore and executed once.

**Screenshots**
- Django Admin showing job added twice
![image](https://user-images.githubusercontent.com/31275429/105385186-e7c50380-5bc7-11eb-904d-a47740ae0964.png)

**Comment by jcass77** [comment]
Running APScheduler background jobs in multi-threaded environments (like webapps) is inherently unsafe.

The README contains full details.
