### ISSUE TITLE
[Question] How to run apscheduler while using gunicorn by sysmtemd?

### ISSUE THREAD

**Issue by gotounix** [jcass77/django-apscheduler#135]
In README:

> This management command should be invoked via ./manage.py runapscheduler whenever the web server serving your Django application is started. The details of how and where this should be done is implementation specific, and depends on which web server you are using and how you are deploying your application to production. For most people this should involve configuring a supervisor process of sorts.

### Question 1

While I using systemd or supervisord start my django project, and how to start apscheduler? Just run the command `./manage.py runapscheduler`  after django project instance running successful?

And while supervisord restart django project, how to auto run apscheduler again?

### Question 2:

I try run `schedule.start()`  in `apps.py` while project ready, but only the tasks that will be performed in a short period of time will be performed. After the tasks is executed, the tasks of the next cycle will be generated, but they will not be executed and will not generate tasks of the next next cycle.

```
class SchedulerConfig(AppConfig):
    name = 'business.scheduler'

    def ready(self):
        if os.environ.get('RUN_MAIN', None) != 'true':
            from .views import scheduler
            scheduler.start()
```

**Comment by jcass77** [comment]
> ./manage.py runapscheduler after django project instance running successful?

Yes.

> And while supervisord restart django project, how to auto run apscheduler again?

You don't generally need to restart django-apscheduler every time that your Django app is restarted. This will only be necessary if you made changes to a static apscheduler schedule in your Python code.

I don't think supervisord supports dependencies but you should be able to restart processes in tandem using systemd.

> After the tasks is executed, the tasks of the next cycle will be generated, but they will not be executed and will not generate tasks of the next next cycle.

I am not sure I follow, could you elaborate on what you are trying to achieve?

If you are starting schedulers in Django views, and the views end up being served by different gunicorn webserver processes, then the schedulers won't know about each other and also won't properly coordinate sharing one central persistent job store.

We are waiting for the [upcoming APScheduler 4.0 release](https://github.com/agronholm/apscheduler/issues/465), which should hopefully allow us to share a persistent job store among multiple schedulers.

**Comment by gotounix** [comment]
@jcass77 Thanks for your reply.
In `Question 2`, I'm not starting scheduler in Django views, I'm starting scheduler while the app registry is fully populated by overriding `ready()` function, and I used `--preload` in gunicorn that let all jobs run on one worker.

But the result is the recently jobs will execute successful, and the new jobs generated for next cycle will not run. It looks the scheduler is shutdown.

**Comment by jcass77** [comment]
Can’t say for sure but I would speculate that gunicorn might be killing the background scheduler threads that are being spawned from the main webserver process.

It might interpret a long-running thread as misbehaving in some way, and decide to kill it or restart the worker process to try to resolve.

Most webservers expect to be serving stateless responses to HTTP requests that only run for a few seconds, as opposed to maintaining background threads between responses.

**Comment by gotounix** [comment]
@jcass77 I don't known whether you are right. But I used `flask-apscheduler` under gunicorn, everything works well.
I tried `python manage.py runapscheduler` while I found the jobs can't execute, and it returns `Scheduler is already running`.

**Comment by jcass77** [comment]
Closing now - please re-open if there is any new information that you would like to share.
