### ISSUE TITLE
Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by merlin2002** [jcass77/django-apscheduler#137]
Error getting due jobs from job store 'default': (2013, 'Lost connection to MySQL server during query')

**Comment by merlin2002** [comment]
wait_timeout  is 28800, schedule interval is 24 hours

scheduler = BackgroundScheduler()
scheduler.add_jobstore(DjangoJobStore(), "default")
scheduler.add_job(sendemail.main, 'cron', day_of_week='mon-sun', hour='08', minute='00', replace_existing=True,
                  id='auto_biz_ops_dept', name="test",
                  args=[[x.mail for x in receivers], 'test', 'test'])
scheduler.start()

**Comment by jcass77** [comment]
I can't think of anything specific to django-apscheduler that could be causing this issue.

In general though, using a `BackgroundScheduler` in a web application is inherently problematic as you do not have any control over how the web application server will manage any long-running threads / processes that APScheduler spawns in the background (have a look at the README for an alternative approach).

The discussion in https://github.com/encode/uvicorn/issues/292 might also be of interest.

Please re-open if there is any more relevant detail that you can add that is not covered by the above.
