### ISSUE TITLE
make migrate error for MongoDB

### ISSUE THREAD

**Issue by 962725312** [jcass77/django-apscheduler#138]
I find if we use MongoDB as the project's database, the error will happen when we import this module and make migrate.That's because id is MongoDB's default primary key.After the table created, we can't insert a new column called "id".That means we should delete all the files in /django-apscheduler/migrations and then make migrations django-apscheduler. It can resolve this error.But it's not convinient, there maybe a commit for this error for pip.

**Comment by jcass77** [comment]
MongoDB is unfortunately [not officially supported by the Django project](https://docs.djangoproject.com/en/3.0/ref/databases/#databases).

It is of course possible that you can successfully use MongoDB with many Django projects, and even get it to work with django-apscheduler.

We are just not in a position to verify and ensure support for every 3rd party database backend out there.
