### ISSUE TITLE
Lost connection to MySQL When using the DjangoJobStore

### ISSUE THREAD

**Issue by Tesla-lu** [jcass77/django-apscheduler#143]
**Describe the bug / feature**
Lost connection to MySQL When using the DjangoJobStore,
but it worked when i don't call add_jobstore() function (I known the default jobstore class is MemoryJobStore)

**To Reproduce**
flow is part of my codes (which copy from runapscheduler.py part of README.md):
scheduler = BlockingScheduler(timezone=settings.TIME_ZONE)
scheduler.add_jobstore(DjangoJobStore(), "default")

the mysql connection is lost when i add a jobstore by DjangoJobStore
flow is errors:
Error getting due jobs from job store 'default': (2013, 'Lost connection to MySQL server during query')
Error getting due jobs from job store 'default': (0, '')

**Expected behavior**
the mysql connection is lost when i add a jobstore by DjangoJobStore

**Screenshots**
Error getting due jobs from job store 'default': (2013, 'Lost connection to MySQL server during query')
Error getting due jobs from job store 'default': (0, '')

**Comment by jcass77** [comment]
Are you launching the scheduler with `python manage.py runapscheduler`?

**Comment by Tesla-lu** [comment]
Yeap， error&nbsp; raise&nbsp; when my_job cron set&nbsp;
secend='*/50'&nbsp;

---Original---
From: "John ***@***.***&gt;
Date: Mon, May 3, 2021 22:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jcass77/django-apscheduler] Lost connection to MySQL When using the DjangoJobStore (#143)




 
Are you launching the scheduler with python manage.py runapscheduler?

**Comment by jcass77** [comment]
Sorry I can't make sense of the response posted above.

**Comment by Tesla-lu** [comment]
here is my code:
class Command(BaseCommand):
    help = "Runs apscheduler."

 
class Command(BaseCommand):
    help = "Runs apscheduler."

    def add_arguments(self, parser):
        parser.add_argument('line_args', nargs='*', type=str)

    #@no_translations
    def handle(self, *args, **options):
        from apps.cron import sync_job
        line_args = options.get("line_args")
        print(f"=== args: {line_args}")
        scheduler = BlockingScheduler(timezone=settings.TIME_ZONE)
        # scheduler = BackgroundScheduler(timezone=settings.TIME_ZONE)
        scheduler.add_jobstore(DjangoJobStore(), "default")
        

        scheduler.add_job(
            my_job,
            trigger=CronTrigger(second="*/50"),  # Every 50 seconds
            id="my_job",  # The `id` assigned to each job MUST be unique
            max_instances=1,
            replace_existing=True,
        )
        logger.info("Added job 'my_job'.")

        scheduler.add_job(
            delete_old_job_executions,
            trigger=CronTrigger(
                day_of_week="mon", hour="00", minute="00"
            ),  # Midnight on Monday, before start of the next work week.
            id="delete_old_job_executions",
            max_instances=1,
            replace_existing=True,
        )
        logger.info(
            "Added weekly job: 'delete_old_job_executions'."
        )

        scheduler.add_job(sync_job.sync_org,
                          trigger=CronTrigger(
                              day="*", hour="*",
                              minute="00",
                              second="10"
                          ),
                          id="sync_org",
                          max_instances=1,
                          replace_existing=True,
                          # jobstore="djangojobstore"
                          )

        try:
            logger.info(f"=== {scheduler.get_jobs()}")
            logger.info("=== Starting scheduler...")
            scheduler.start()

        except KeyboardInterrupt:
            logger.info("=== Stopping scheduler...")
            scheduler.shutdown()
            logger.info("=== Scheduler shut down successfully!")

**Comment by Tesla-lu** [comment]
then,  python manage.py runapscheduler

then  raise :  Error getting due jobs from job store 'default': (2013, 'Lost connection to MySQL server during query')
Error getting due jobs from job store 'default': (0, '')

**Comment by jcass77** [comment]
I don't see any obvious problems with the code snipped that you have posted above, and suspect that the issue might be related to how the database connection has been configured for your application.

Maybe take a look at the official Django docs for some general [database-related](https://docs.djangoproject.com/en/3.2/ref/databases/#mysql-notes) guidelines.

**Comment by jcass77** [comment]
...especially the section on [persistent connections](https://docs.djangoproject.com/en/3.2/ref/databases/#persistent-connections).

**Comment by Tesla-lu** [comment]
need call close_old_connections before you use database connection or use model when use django model or database connection without a django request 
'Lost connection' error will raise  fore a long time to next job, if  you don't call close_old_connections()
close_old_connections() will be called by django [signals ](signals) in the django request

flow is my new code
```
class MyStore(DjangoJobStore):
    def _get_jobs(self, *args, **kwargs):
        from django.db import close_old_connections, reset_queries
        reset_queries()
        close_old_connections()
        return super()._get_jobs(**kwargs)


from django.db import  reset_queries, close_old_connections
def my_job(**kwargs):
    # reset_queries()
    reset_queries()
    close_old_connections()
```

**Comment by jcass77** [comment]
See [this post](https://forum.djangoproject.com/t/closing-old-db-connections-outside-of-the-request-context/299) on the Django forums:

> Connections are stateful - they can contain open transactions/savepoints, temporary variable, settings, CTE’s, and tables. Because of this state, especially open transactions/savepoints, I don’t think it would make sense, across all db backends and usecases, to call close_old_connections when a QuerySet is evaluated.

The workaround that you are suggesting might be fine to use in your specific usecase, but it might not be prudent to suggest that as a catch-all for everybody.

I suspect that the best approach would be to make use of a database connection pooler (e.g. [pgbouncer](https://www.pgbouncer.org) if using PostgreSQL - not sure if there is an obvious choice for MySQL).
