### ISSUE TITLE
Execute scheduler.start() in app.ready() raise Exception

### ISSUE THREAD

**Issue by zmmfsj-z** [jcass77/django-apscheduler#150]
When I run 'python manage.py migrate' (I'm runing my django project to a new server)
raise django.db.utils.ProgrammingError: Error: The relationship "django_apscheduler_djangojobexecution" does not exist
eg: scheduler.start() in app.ready()

**Comment by jcass77** [comment]
Starting a scheduler inside one of your other Django apps is not safe, and not recommended. Please refer to the README for details.

In your specific instance, the scheduler is probably trying to start up before the migration command has had a chance to finish (but you are likely to encounter other issues with that approach as well).
