### ISSUE TITLE
‘python manage.py migrate django_apscheduler zero’ raise Excetion:

### ISSUE THREAD

**Issue by zmmfsj-z** [jcass77/django-apscheduler#152]

**Comment by jcass77** [comment]
Please confirm that you are using one of the databases that are [officially supported by Django](https://docs.djangoproject.com/en/3.2/ref/databases/).

**Comment by jcass77** [comment]
...I just noticed that you are trying to unapply migrations. It could be that reversing that specific migration is not supported in Django.

I personally do not have any experience with finding workarounds for that particular limitation.

**Comment by jcass77** [comment]
Not much we can do if Django support is not available - closing.
