### ISSUE TITLE
Jobs not executed when PostgreSQL conf is reloaded

### ISSUE THREAD

**Issue by pisaia01** [jcass77/django-apscheduler#159]
**Describe the bug / feature**
When PostgreSQL configuration is reloaded, new tasks are marked as "Started execution" but are not actually executed. Is there any way to solve this? Or at least re-start apscheduler remotely? (i.e. without having access to the Server, restart them from admin panel)

**To Reproduce**
1. On the PostgreSQL Server run `SELECT pg_reload_conf();`
2. Go to Admin Panel (or in the django_apscheduler_djangojobexecution table)
3. You will notice that any new job that is about to executed after you run the reload is correctly registered in the table as "Started execution" but it will be never executed, and remains as "Started execution"

**Expected behavior**
Prevent this completely or if not possible it will be better if there is a way to restart the apscheduler remotely (i.e. without having to access the server since we might not have direct access to the server due to the fact that only the IT personnel might have access) 

**Screenshots**
![Scheduler](https://user-images.githubusercontent.com/28766290/143262143-3fd01642-5da5-45a2-a4c5-d39e1736314c.PNG)

**Comment by jcass77** [comment]
django-apscheduler relies on the standard Django database backend functionality and does not implement any special connection management features.

Maybe check out the [databases](https://docs.djangoproject.com/en/dev/ref/databases/#general-notes) section of the official Django docs. You might get it to work by fiddling with `CONN_MAX_AGE` but this project won't be able to support edge cases like this directly.
