### ISSUE TITLE
django-apscheduler not working with sqlserver

### ISSUE THREAD

**Issue by saranmaikalluri** [jcass77/django-apscheduler#160]
Not able to run migrations for django-apscheduler with sql server as backend. After installing, every time in try to run

python manage.py migrate.. I get the below error..

NotImplementedError: the backend doesn't support altering from/to AutoField.

How to use django-apscheduler with sql server as backend???

**Comment by jcass77** [comment]
MS SQL server is not supported - please refer to the README for details.
