### ISSUE TITLE
pytz is deprecated in Django 4.0

### ISSUE THREAD

**Issue by ravisumit33** [jcass77/django-apscheduler#161]
With latest Django has deprecated `pytz` in favour of `timezone`. How are we going to handle this since `APScheduler` needs `pytz` ?

**Comment by jcass77** [comment]
I'm not sure that there is a 100% overlap in features / functionality between `pytz` and `timezone` - we should be able to keep our dependency without any issues.

Happy to look at any PR's that aim to get rid of `pytz` if anybody is interested.

**Comment by jcass77** [comment]
Closing for now. Please re-open if anybody comes across any actually issues related to our continued reliance on `pytz`.
