### ISSUE TITLE
PytzUsageWarning on Startup

### ISSUE THREAD

**Issue by CharlesFr** [jcass77/django-apscheduler#164]
Every time the scheduler starts I get the following warning:

```
/app/.heroku/python/lib/python3.8/site-packages/apscheduler/triggers/cron/__init__.py:146: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
```

Is this due to bad setup on my behalf or is there a bug?

**Comment by jcass77** [comment]
This is probably related to #161: we need to remove the dependency on `pytz` eventually though I am not sure if there is a hard deadline by which that should be done.

**Comment by CharlesFr** [comment]
Thanks @jcass77  - is there anything I can do in the meantime to supress this error?

**Comment by jcass77** [comment]
It's a warning, not an error, so you can just ignore it.

If staring at the warning really bothers you then you can [enable a warning filter](https://docs.python.org/3/library/warnings.html#default-warning-filter) to suppress it completely.

But this has the drawback of also hiding other deprecation warnings that you might care more about and is probably not advisable.
