### ISSUE TITLE
Feat: Add management command to clean up job execution table

### ISSUE THREAD

**Issue by hugorodgerbrown** [jcass77/django-apscheduler#166]
**Describe the bug / feature**
We have nearly 2m job execution records in our `django_apscheduler_djangojobexecution`
table, and the vast majority of these are redundant from an audit point of view - they
are just taking up space.

It would be nice to have a management command that could run nightly to truncate 
the table using various criteria. The builtin Django `clear_sessions` command is
the sort of thing I am thinking of. We will be building one ourselves to do this,
so am really asking whether it's something you would be interested in?

**To Reproduce**

Delete all executed records
`$ python manage.py clear_job_executions`

Delete all error records
`$ python manage.py clear_job_executions --status=error`

Delete all executed records for a specific job_id
`$ python manage.py clear_job_executions --status=executed --job=job_id`

Delete all executed records except a specific job_id
`$ python manage.py clear_job_executions --job=-job_id`

**Expected behavior**
The job execution table is maintained at a manageable size.

**Comment by jcass77** [comment]
Have you perhaps looked at the example `delete_old_job_executions` job that is described in the README? It can be scheduled to run on a regular basis and ensure that the table size remains manageable given your specific requirements.

This does not provide the fine-grained level of control that you described above though, but it should meet most people's needs for performing basic maintenance.

Consider submitting a PR for the rest?

**Comment by hugorodgerbrown** [comment]
Ah - sorry, should have spotted that - looks almost exactly what we want. I'll knock up something for our project and then open a PR once I have something that works.
