### ISSUE TITLE
How to associate django_apscheduler_djangojob with my own model by ForeignKey

### ISSUE THREAD

**Issue by jayt1001** [jcass77/django-apscheduler#168]
like this：
![165487026-817a861e-3d19-4c23-ac3c-2ea40bc56a6f](https://user-images.githubusercontent.com/29675005/165497332-6d570223-d982-425b-ad7c-0576ff1aea01.png)

**Comment by jcass77** [comment]
I'm not sure I understand the question - could you perhaps elaborate on what you are trying to achieve?

Closing as this is not an actual bug report. Please re-open if still relevant.
