### ISSUE TITLE
Job automatically disappeared in random time 

### ISSUE THREAD

**Issue by lodye509** [jcass77/django-apscheduler#169]
Hi all, I am trying to figure the reason why the jobs are disappeared from scheduler(all the record disappeared from table). 

I'm working on a project with couple other people, but I'm the only one touched scheduler code. In this scheduler, I have added one daily job, one weekly job, and the delete_old_job_executions job which run weekly. But somehow, sometimes all the daily job will disappeared from the table(not right after delete_old_job_executions job), and after carefully check on the code, I still have no cue on how they been removed.

I was thought maybe someone has the older version code, but i have tried comment out the code, it won't impact the job already added to scheduler. And seems like only remove() will do the remove job work.

Does any one have any idea on how the job can be removed? This issue really need to be resolve otherwise I will need to check the database everyday and run job manually which is painful, thank you!

**Comment by jcass77** [comment]
APScheduler will [remove the job](https://apscheduler.readthedocs.io/en/latest/userguide.html#removing-jobs) from the table automatically if there are no more runs scheduled to occur in the future for whatever reason.

If you could post an example of the code that you are using to schedule the job(s) we might be able to assist further.

**Comment by jcass77** [comment]
No updates in over a month - closing.
