### ISSUE TITLE
cron function that is running over 15 seconds is not working 

### ISSUE THREAD

**Issue by MinSiThu** [jcass77/django-apscheduler#174]
**Runtime takes more than 15 seconds**
I set a function to run cron mode in django apscheduler.
I deployed the project with gunicorn on ubuntu os.
But the function is relatively takes some time about 25 seconds to finish.
But django-apscheduler maximum allow time is 15 seconds.

On admin panel, the following is shown
```
Maximum runtime of 15 seconds exceeded! Not all jobs could be completed successfully. Pending jobs: main_function
```

**Code Snippets**
```python
import logging

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.executors.pool import ProcessPoolExecutor, ThreadPoolExecutor
from django_apscheduler.jobstores import DjangoJobStore,register_events, register_job

from django.conf import settings
from .services import main

scheduler = BackgroundScheduler()
scheduler.add_jobstore(DjangoJobStore(), "default")

def start():
    scheduler.add_job(main,"cron",id="main_function",day_of_week="mon-fri",hour=17,minute=30,second=20,replace_existing=True)
    register_events(scheduler)
    scheduler.start()
```

**Expected behavior**
I expect the code to be successfully run even it takes one minute.

**Comment by jcass77** [comment]
This is covered in the [README](https://github.com/jcass77/django-apscheduler#features) - see `APSCHEDULER_RUN_NOW_TIMEOUT`.
