### ISSUE TITLE
DB error executing '_get_jobs' ((2013, 'Lost connection to MySQL server during query')). Retrying with a new DB connection...

### ISSUE THREAD

**Issue by MinSiThu** [jcass77/django-apscheduler#175]
## django-apscheduler cron job running cause lost mysql connection

I have a cron job that is running at 12pm every weekday. After the first time running of the function, database connection is lost and showing the following error code. 

```bash
DB error executing '_get_jobs' ((2013, 'Lost connection to MySQL server during query')). Retrying with a new DB connection...
```

When the time function is running for second time, all other print code lines works,
but at the line of execution the database query, the following error occurs
```bash
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

```
The following is the scheduler code I am working on
```python
import logging

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.executors.pool import ProcessPoolExecutor, ThreadPoolExecutor
from django_apscheduler.jobstores import DjangoJobStore,register_events, register_job

from django.conf import settings
from .services import mainScheduleFor1200

scheduler = BackgroundScheduler()
scheduler.add_jobstore(DjangoJobStore(), "default")

def start():
    scheduler.add_job(mainScheduleFor1200,"cron",id="main",day_of_week="mon-fri",hour=12,minute=1,second=20,replace_existing=True)
    register_events(scheduler)
    scheduler.start()
```

**Comment by MinSiThu** [comment]
I set the mysql interactive_timeout as 
```sql
SET @@GLOBAL.interactive_timeout=31536000
```

**Comment by jcass77** [comment]
The README [provides some guidance](https://github.com/jcass77/django-apscheduler#database-connections-and-timeouts) on managing DB connections.

Behavior for running a BackgroundScheduler in a Django app or view is unpredictable and not officially supported.

**Comment by MinSiThu** [comment]
## Solved

I close the connection after the execution of the function.
The following code snippet is added at the end of the **mainScheduleFor1200** 

```python
from django.db import connection
connection.close()
print("Closed the connection")
print("Exit function")
```
