### ISSUE TITLE
AttributeError("'zoneinfo.ZoneInfo' object has no attribute 'localize'") and 'dict' object has no attribute 'has_header'

### ISSUE THREAD

**Issue by RaulS0sa** [jcass77/django-apscheduler#177]
**Describe the bug / feature**
Exception AttributeError("'zoneinfo.ZoneInfo' object has no attribute 'localize'") is triggered at scheduler.start() when running the managment command using a url returns 'dict' object has no attribute 'has_header'

**To Reproduce**
1. add a new app to a django aplication 
2. add managment job to app as described 
3. in app's views add management.call_command("runapscheduler")
3. call the url attached to the view

**Expected behavior**
scheduler runs

**Screenshots**
![Screen Shot 2022-11-09 at 11 19 32](https://user-images.githubusercontent.com/53208514/200897614-ffef4209-5f02-4109-8f96-7d78ce314c9f.png)
![Screen Shot 2022-11-09 at 11 23 58](https://user-images.githubusercontent.com/53208514/200898551-83c9fc91-fc6e-49b0-891f-81f1d756f7a7.png)

**Comment by jcass77** [comment]
It is likely that this AttributeError is arising somewhere in your code though it is hard to tell from the detail provided. 

Sorry for the tardy response - I am going to close this issue given the long period of inactivity but please reopen if you have more to share.

*On an unrelated note, you [shouldn't be starting up a scheduler inside of a view](https://github.com/jcass77/django-apscheduler?tab=readme-ov-file#common-footguns), which could result in multiple schedulers competing to run the same jobs.*
