### ISSUE TITLE
ModuleNotFoundError: No module named 'backports'

### ISSUE THREAD

**Issue by glacier-ji** [jcass77/django-apscheduler#179]
python version: 3.10
Django version: 3.2

I upgrade the python version from python 3.7 to 3.10,   when I start the project,   the job will be removed from DB, and then the error showed blow, how to solve it? please

> Unable to restore job '183236ac-8d74-11ed-8401-2a7f7dc9b7cf'. Removing it...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django_apscheduler/jobstores.py", line 295, in _get_jobs
    jobs.append(self._reconstitute_job(job_state))
  File "/usr/local/lib/python3.10/site-packages/django_apscheduler/jobstores.py", line 279, in _reconstitute_job
    job_state = pickle.loads(job_state)
ModuleNotFoundError: No module named 'backports'

**Comment by jcass77** [comment]
Looks like a missing dependency. If you upgraded your Python interpreter you could try running `pip install django-apscheduler` again to refresh everything.

Closing as django-apscheduler does not take a direct dependency on `backports` itself.
