### ISSUE TITLE
Trigger scheduled job to be executed manually

### ISSUE THREAD

**Issue by n4ff4h** [jcass77/django-apscheduler#184]
I was wondering if I could perhaps trigger a job execution with a click of a button. Idk if this is a limitation since the apscheduler will be separated with the web server as per the recommended approach in the docs.

**Comment by jcass77** [comment]
The README shows an example of triggering a job manually via the DjangoJob admin page.

**Comment by n4ff4h** [comment]
I want to extend the same functionality to my own templates. Is it as simple as updating the next_run datetime value?

**Comment by n4ff4h** [comment]
Is it possible to extend this to my own templates?

**Comment by jcass77** [comment]
> Is it possible to extend this to my own templates?

I am not sure what you are aiming for, but hope the provided example is useful.
