### ISSUE TITLE
DjangoJobStore Randomly Deletes Jobs

### ISSUE THREAD

**Issue by unitedsoftworks** [jcass77/django-apscheduler#188]
I have apscheduler running with a DjangoJobStore from a management command in django, but every so often some (not all) of the jobs will delete themselves.

The scheduler still runs, still gets other jobs, but doesnt find the specific one in the code below.
When i check the admin, its deleted.

Restarting the code fixes it as it adds the job back for a random amount of time before deleting again.

I added a listener for EVENT_JOB_REMOVED and it is never fired, and i added breakpoints in all the delete methods for DjangoJob and none of them ever hit. 

the function must_reply simply checks an email inbox and sends a reply back over smtp, nothing in there accesses the DjangoJob table, nor does anything in the rest of the code.

must_reply is decorated with @close_old_connections

removing DjangoJobStore as a job store fixes the problem, but obviously I would like to use it haha

It is truly strange.

```
class Command(BaseCommand):
    help = "Runs APScheduler."

    def handle(self, *args, **options):


   
            executors = {
                'default': ThreadPoolExecutor(max_workers=10)
            }

            job_defaults = {
                'coalesce': True,
                'misfire_grace_time': 10

            }

            scheduler = BlockingScheduler(timezone=settings.TIME_ZONE, executors=executors, job_defaults=job_defaults)

            scheduler.add_jobstore(DjangoJobStore(), "default")


            scheduler.add_job(
                must_reply,
                IntervalTrigger(
                    seconds=10
                ),
                id="must_reply",
                max_instances=1,
                replace_existing=True,
            )


            try:
                scheduler.start()
            except:
   
                scheduler.shutdown()
                pass

```

**Comment by unitedsoftworks** [comment]
update i finally found an error

`"module backports not found"`
inside of 

`jobs.append(self._reconstitute_job(job_state))`

but this happens randomly during execution, and then it runs the code
```
# Remove all the jobs we failed to restore
if failed_job_ids:
    logger.warning(f"Removing failed jobs: {failed_job_ids}")
    DjangoJob.objects.filter(id__in=failed_job_ids).delete()
```

**Comment by eduardopdev** [comment]
Hello. Are you still having this problem?

**Comment by eduardopdev** [comment]
@unitedsoftworks wich versions of django and django-apscheduler are you running?

**Comment by jcass77** [comment]
Closing due to lack of response - please reopen if required.

**Comment by jcass77** [comment]
Looks like a missing Python dependency. If you made changes to you Python environment recently you could try running `pip install django-apscheduler` to refresh everything.
