### ISSUE TITLE
New maintainers wanted

### ISSUE THREAD

**Issue by jcass77** [jcass77/django-apscheduler#190]
It has been a few years since I have worked on any Django applications in production and I am not making use of this 
codebase myself anymore.

If you are interested in becoming a maintainer then please comment on this issue and provide some details on:

- how you are currently using django-apscheduler
- how long you have been a user for, and 
- if there are reasonable prospects of you continuing to be a user for the foreseeable future

The ideal scenario would be for me to transfer ownership of the repository to a new owner who is invested in keeping django-apscheduler going to meet their own needs and those of the community.

Thank you for your support over the years.

**Comment by eduardopdev** [comment]
Hello. I am a software developer from Brazil working mainly with Django. Some of the projects on make use of this package and I would be happy to be responsible for maintaining it.

**Comment by jcass77** [comment]
Thank you Eduardo, I have added you as a collaborator.

**Comment by TGoddessana** [comment]
hello. I'm working as a freelance backend developer in South Korea and have been making small and big contributions to the django and python ecosystem like drf, cookiecutter diango, jwt packages over the past few years. 

I've been using this app for corporate assignments for recruitment for the past period and would like to keep it compatible with the latest python and django versions.

**Comment by jcass77** [comment]
Thank you @TGoddessana, I have added you as a contributor.

**Comment by TGoddessana** [comment]
@jcass77 hi, thanks for adding me as a contributor. there are some questions...

1. the default branch of this repository is develop, is it okay to change default branch to main?
2. is it okay to merge `develop` branch to `main`?
3. how can we publish a new version? i just added the tests to cover python3.8 to python3.12 and django4.2 to django5.1, but i'm not sure publish a new version is okay.


---
+ now i added github actions to use tox and python3.8 ~ python3.12, Do you have a merge rule or release order in mind?

![image](https://github.com/user-attachments/assets/624c7453-95b5-471b-940f-cbfed9630285)

**Comment by jcass77** [comment]
Have a look at https://github.com/jcass77/django-apscheduler/blob/develop/docs/releasing.md, which explains the release procedures and how to merge `develop` into `main` as part of cutting a new release.

I would drop Python 3.8, which will [reach end of support in October](https://www.python.org/downloads/).

**Comment by JaeHyuckSa** [comment]
@jcass77 Hello! I am currently working at an EdTech company in South Korea, where we actively use Django, including django-apscheduler, to handle scheduling tasks. I have been using Django for the past few years and have consistently contributed to Django and related libraries. I would love to help and become a maintainer of this project.

**Comment by TGoddessana** [comment]
Thanks for the great material, I've read through it.

maybe we can check #191 , which supports newer python and django versions.. 

What I think is important, and what I was wondering, is what the sequence of actions are for releasing a new version of a package.

**Comment by kingmo888** [comment]
Hello, I am a Django project developer from China. My open-source Django project has received over 700 stars within a year.
Project link: [rustdesk-api-server](https://github.com/kingmo888/rustdesk-api-server)

My GitHub stats are as follows:
![GitHub Stats](https://github-readme-stats.vercel.app/api?username=kingmo888&show_icons=true&theme=dracula)

In my opinion, django-apscheduler is a very important cross-platform scheduling project in the Django ecosystem, and I hope it continues to grow and help more people. Therefore, when I saw the developer's update, I wanted to contribute my efforts to it.

**Comment by jcass77** [comment]
[Release v0.7.0](https://github.com/jcass77/django-apscheduler/releases/tag/v0.7.0) has been cut and the test suite is passing against Python 3.9 - 3.12 and Django >= 4.2.

Thank you @eduardopdev and @TGoddessana for stepping forward and helping out.

With two new collaborators I think we can close this issue as resolved.
