### ISSUE TITLE
how to save task result to [Django job executions]

### ISSUE THREAD

**Issue by shifenhutu** [jcass77/django-apscheduler#193]
**Describe the bug / feature**
in my task, i return a data , i hope save the data to django

# my hope 
when i in my task return a data
![image](https://github.com/user-attachments/assets/45b0e41f-a0d8-4f7a-9b1a-ec8f275b6c32)

i hope i can  see the data in [Django job executions]
![image](https://github.com/user-attachments/assets/e7b6f8db-dd09-4e7a-9ec8-d091a6d2d3f8)

thank you very much

**Comment by TGoddessana** [comment]
Hi. 
- It looks like you've already implemented the functionality you're looking for, is that correct? 
- What's the difference between creating a model for storing the jobs of "my_job2222" and storing the return result of a function, as you suggested?

I would like to hear a more detailed use case.

**Comment by shifenhutu** [comment]
@TGoddessana 

i am sorry for my bad english 

i haven't already implemented that

i  used chrome F12  to make this UI  

-----

in  https://github.com/celery/django-celery-results  , it will save the result to django-db,
```


# app/tasks.py
from celery import shared_task
import time

@shared_task
def add(x, y):
    time.sleep(2)
    return x + y  #   [django-celery-results] will be save result to django db

```

```
# app/views.py
from .tasks import add

def test_celery(request):
    add.delay(3, 5)
    return HttpResponse("Celery works")

# app/urls.py
urlpatterns = [
    re_path(r'^test/$', views.test_celery, name="test_celery")
]
```


### django admin => django-celery-results => task detail
![image](https://github.com/user-attachments/assets/a9a049f4-b8bf-4888-96cb-4cd8b7f717fb)


thank you very much

**Comment by shifenhutu** [comment]
i find https://github.com/django-q2/django-q2   it can save the result to django db 

![image](https://github.com/user-attachments/assets/3afbfdbd-7342-4ab8-a044-6fe3183bde84)

**Comment by TGoddessana** [comment]
@shifenhutu 

Sorry for the delay. I'm glad that you found a nice solution for your project.

As you said, a new migration file is required to add the new fields to the database. This can be a load under a system that already has tons of rows (of course, I believe it's the role of the owner of that Django project to review and apply new migrations, not the role of the maintainer of django-apscheduler 😅).

But I think this feature is quite useful and nice, maybe we can implement it in the project? @jcass77 would love to hear your thoughts 😀
