### ISSUE TITLE
Jobs once added to `django_apscheduler_djangojob` are never removed when restarting the scheduler

### ISSUE THREAD

**Issue by kevinrenskers** [jcass77/django-apscheduler#194]
I have a Django project with a whole bunch of scheduled jobs, all running using `django-apscheduler`. Some of these jobs are only meant to run in production, and as such there's an `if settings.ENVIRONMENT == "PRODUCTION"` check before adding them using `scheduler.add_job`. This works fine.

Here's the problem: when we imported the production database into our staging database, we copied all data, so that includes the entries in `django_apscheduler_djangojob`. And from that moment on, those production-only jobs were now also running in the staging environment, because those jobs were part of `django_apscheduler_djangojob`, with a `next_run_time` value and all. That's surprise number one: it's not the code that determines when something runs, it's purely this database table.

Surprise number two was that restarting the scheduler process did NOT remove these jobs from `django_apscheduler_djangojob`, even though according to the code they shouldn't be added. So, it seems that once a job is in the `django_apscheduler_djangojob` table, it'll never be removed, and it'll just keep executing, even though according to the code this job doesn't even exist (because of the `settings.ENVIRONMENT` check). I'd expect that running `./manage.py runapscheduler` would "sync" the database entries with the current state of the code.

Here's how I reproduced it:

1. Add two jobs to the scheduler, run `./manage.py runapscheduler` (I'm using the example `runapscheduler.py` from the readme)
2. Check the `django_apscheduler_djangojob` table: both jobs are there as expected
3. Change the code to remove one of the jobs from the scheduler. Not the entire job function, just the `scheduler.add_job` call for it
4. Restart `./manage.py runapscheduler`
5. Check the `django_apscheduler_djangojob` table: both jobs are still in there

**Comment by jcass77** [comment]
> That's surprise number one: it's not the code that determines when something runs, it's purely this database table.

Yes, the purpose of the job store (whether in memory or in the Django database) is to maintain the 'schedule' of when jobs should run. This behaviour is determined by APScheduler itself.

> ...restarting the scheduler process did NOT remove these jobs from `django_apscheduler_djangojob`

This is expected. If you want to update or remove existing jobs then you should do so via the methods provided (see https://github.com/jcass77/django-apscheduler/blob/develop/django_apscheduler/jobstores.py#L246-L274) for some ideas.

Keep in mind that the main use case of persisting the job store to database is to make it durable, and have it persist between application restarts. If you want to mutate or remove the schedule then you need to do so explicitly.

In your case you probably want something like:

```
if settings.ENVIRONMENT != "PRODUCTION"
    # Remove the jobs that should only run in production environments.
    ...
```
